In [1]:
import kaggle

OSError: Could not find kaggle.json. Make sure it's located in C:\Users\karti\.kaggle. Or use the environment method.

In [2]:
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading orders.csv.zip to C:\Users\karti\Kartik Data Analyst

  0%|          | 0.00/200k [00:00<?, ?B/s]
100%|##########| 200k/200k [00:00<00:00, 272kB/s]
100%|##########| 200k/200k [00:00<00:00, 272kB/s]

In [7]:
# extracting data from zip file
import zipfile
zip_ref = zipfile.ZipFile('orders.csv.zip') 
zip_ref.extractall() # extract file to dir
zip_ref.close() # close file

TypeError: ZipFile.__init__() got an unexpected keyword argument 'na_values'

In [9]:
import pandas as pd 
df=pd.read_csv('orders.csv',na_values=['Not Available','unknown'])
df.head(20)

    Order Id  Order Date       Ship Mode      Segment  ... cost price List Price Quantity  Discount Percent
0          1  2023-03-01    Second Class     Consumer  ...        240        260        2                 2
1          2  2023-08-15    Second Class     Consumer  ...        600        730        3                 3
2          3  2023-01-10    Second Class    Corporate  ...         10         10        2                 5
3          4  2022-06-18  Standard Class     Consumer  ...        780        960        5                 2
4          5  2022-07-13  Standard Class     Consumer  ...         20         20        2                 5
5          6  2022-03-13             NaN     Consumer  ...         50         50        7                 3
6          7  2022-12-28  Standard Class     Consumer  ...         10         10        4                 3
7          8  2022-01-25  Standard Class     Consumer  ...        860        910        6                 5
8          9  2023-03-23             NaN     Consumer  ...         20         20        3                 2
9         10  2023-05-16  Standard Class     Consumer  ...         90        110        5                 3
10        11  2023-03-31             NaN     Consumer  ...       1470       1710        9                 3
11        12  2023-12-25             NaN     Consumer  ...        750        910        4                 3
12        13  2022-02-11  Standard Class     Consumer  ...         20         20        3                 3
13        14  2023-07-18  Standard Class     Consumer  ...        360        410        3                 2
14        15  2023-11-09             NaN  Home Office  ...         60         70        5                 5
15        16  2022-06-18  Standard Class  Home Office  ...          0          0        3                 5
16        17  2022-02-04  Standard Class     Consumer  ...        610        670        6                 3
17        18  2023-08-04    Second Class     Consumer  ...         60         60        2                 4
18        19  2022-01-23    Second Class     Consumer  ...         10         10        2                 4
19        20  2022-01-11    Second Class     Consumer  ...        170        210        3                 3

[20 rows x 16 columns]

In [10]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [18]:
#rename the column name for best practice
#df.rename(columns={'Order Id':'order_id', 'City':'city'}) manual effort take more time 
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(" ", "_")

In [19]:
df.head()

   order_id  order_date       ship_mode    segment  ... cost_price list_price quantity  discount_percent
0         1  2023-03-01    Second Class   Consumer  ...        240        260        2                 2
1         2  2023-08-15    Second Class   Consumer  ...        600        730        3                 3
2         3  2023-01-10    Second Class  Corporate  ...         10         10        2                 5
3         4  2022-06-18  Standard Class   Consumer  ...        780        960        5                 2
4         5  2022-07-13  Standard Class   Consumer  ...         20         20        2                 5

[5 rows x 16 columns]

In [28]:
#derive new columns for discont
df['discount']=(df['list_price']*df['discount_percent'])/100
df['sales_price']=df['list_price']-df['discount']
df['profit']=df['sales_price']-df['cost_price']

In [29]:
df.head()

   order_id  order_date       ship_mode    segment  ... discount_percent discount sales_price  profit
0         1  2023-03-01    Second Class   Consumer  ...                2      5.2       254.8    14.8
1         2  2023-08-15    Second Class   Consumer  ...                3     21.9       708.1   108.1
2         3  2023-01-10    Second Class  Corporate  ...                5      0.5         9.5    -0.5
3         4  2022-06-18  Standard Class   Consumer  ...                2     19.2       940.8   160.8
4         5  2022-07-13  Standard Class   Consumer  ...                5      1.0        19.0    -1.0

[5 rows x 19 columns]

In [38]:
#drop columns whic are not needed anymore
df.drop(columns=['cost_price','list_price','discount_percent'], inplace=True)

In [58]:
#convert order date to date
df.dtypes

order_id                 int64
order_date      datetime64[ns]
ship_mode               object
segment                 object
country                 object
city                    object
state                   object
postal_code              int64
region                  object
category                object
sub_category            object
product_id              object
quantity                 int64
discount               float64
sales_price            float64
profit                 float64
dtype: object

In [36]:
import pandas as pd
df['order_date']=pd.to_datetime(df['order_date'],format='%Y-%m-%d')

In [40]:
df.head()

   order_id order_date       ship_mode    segment  ... quantity discount sales_price  profit
0         1 2023-03-01    Second Class   Consumer  ...        2      5.2       254.8    14.8
1         2 2023-08-15    Second Class   Consumer  ...        3     21.9       708.1   108.1
2         3 2023-01-10    Second Class  Corporate  ...        2      0.5         9.5    -0.5
3         4 2022-06-18  Standard Class   Consumer  ...        5     19.2       940.8   160.8
4         5 2022-07-13  Standard Class   Consumer  ...        2      1.0        19.0    -1.0

[5 rows x 16 columns]

In [45]:
#Load the data in sql server 
import sqlalchemy as sal
engine = sal.create_engine('MySQL://Kartik_sales_Insight/master?driver=SQL+SERVER')
conn=engine.connect()

NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:MySQL

In [46]:
pip install mysql-connector-python

Collecting mysql-connector-python
  Obtaining dependency information for mysql-connector-python from https://files.pythonhosted.org/packages/38/b4/44efe46d5aff497b6009e4755a5e26a99fd8fe2769857dffa21fad941767/mysql_connector_python-8.4.0-cp311-cp311-win_amd64.whl.metadata
  Downloading mysql_connector_python-8.4.0-cp311-cp311-win_amd64.whl.metadata (2.0 kB)
Downloading mysql_connector_python-8.4.0-cp311-cp311-win_amd64.whl (14.5 MB)
   ---------------------------------------- 0.0/14.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.5 MB 660.6 kB/s eta 0:00:22
   ---------------------------------------- 0.1/14.5 MB 1.1 MB/s eta 0:00:14
   ---------------------------------------- 0.1/14.5 MB 901.1 kB/s eta 0:00:16
    --------------------------------------- 0.2/14.5 MB 1.1 MB/s eta 0:00:13
    --------------------------------------- 0.2/14.5 MB 1.1 MB/s eta 0:00:13
    --------------------------------------- 0.2/14.5 MB 801.7 kB/s eta 0:00:18
    --------------------------------------- 0.2/14.5 MB 801.7 kB/s eta 0:00:18
    --------------------------------------- 0.2/14.5 MB 801.7 kB/s eta 0:00:18
    --------------------------------------- 0.3/14.5 MB 785.7 kB/s eta 0:00:18
    --------------------------------------- 0.3/14.5 MB 723.4 kB/s eta 0:00:20
   - -------------------------------------- 0.4/14.5 MB 819.2 kB/s eta 0:00:18
   - -------------------------------------- 0.5/14.5 MB 829.2 kB/s eta 0:00:17
   - -------------------------------------- 0.5/14.5 MB 800.3 kB/s eta 0:00:18
   - -------------------------------------- 0.5/14.5 MB 830.7 kB/s eta 0:00:17
   - -------------------------------------- 0.7/14.5 MB 975.9 kB/s eta 0:00:15
   -- ------------------------------------- 0.7/14.5 MB 1.0 MB/s eta 0:00:14
   -- ------------------------------------- 0.9/14.5 MB 1.1 MB/s eta 0:00:13
   -- ------------------------------------- 0.9/14.5 MB 1.1 MB/s eta 0:00:13
   -- ------------------------------------- 1.0/14.5 MB 1.1 MB/s eta 0:00:13
   -- ------------------------------------- 1.1/14.5 MB 1.2 MB/s eta 0:00:12
   --- ------------------------------------ 1.2/14.5 MB 1.2 MB/s eta 0:00:11
   --- ------------------------------------ 1.3/14.5 MB 1.3 MB/s eta 0:00:11
   --- ------------------------------------ 1.4/14.5 MB 1.3 MB/s eta 0:00:11
   ---- ----------------------------------- 1.5/14.5 MB 1.3 MB/s eta 0:00:10
   ---- ----------------------------------- 1.5/14.5 MB 1.3 MB/s eta 0:00:10
   ---- ----------------------------------- 1.6/14.5 MB 1.3 MB/s eta 0:00:10
   ---- ----------------------------------- 1.7/14.5 MB 1.3 MB/s eta 0:00:10
   ----- ---------------------------------- 1.8/14.5 MB 1.4 MB/s eta 0:00:10
   ----- ---------------------------------- 1.9/14.5 MB 1.4 MB/s eta 0:00:10
   ----- ---------------------------------- 2.0/14.5 MB 1.4 MB/s eta 0:00:10
   ----- ---------------------------------- 2.1/14.5 MB 1.4 MB/s eta 0:00:09
   ----- ---------------------------------- 2.1/14.5 MB 1.4 MB/s eta 0:00:09
   ------ --------------------------------- 2.3/14.5 MB 1.4 MB/s eta 0:00:09
   ------ --------------------------------- 2.3/14.5 MB 1.5 MB/s eta 0:00:09
   ------ --------------------------------- 2.4/14.5 MB 1.5 MB/s eta 0:00:09
   ------ --------------------------------- 2.5/14.5 MB 1.5 MB/s eta 0:00:08
   ------- -------------------------------- 2.7/14.5 MB 1.6 MB/s eta 0:00:08
   ------- -------------------------------- 2.8/14.5 MB 1.6 MB/s eta 0:00:08
   -------- ------------------------------- 2.9/14.5 MB 1.6 MB/s eta 0:00:08
   -------- ------------------------------- 3.0/14.5 MB 1.6 MB/s eta 0:00:08
   -------- ------------------------------- 3.1/14.5 MB 1.6 MB/s eta 0:00:07
   -------- ------------------------------- 3.2/14.5 MB 1.6 MB/s eta 0:00:07
   --------- ------------------------------ 3.3/14.5 MB 1.6 MB/s eta 0:00:07
   --------- ------------------------------ 3.4/14.5 MB 1.6 MB/s eta 0:00:07
   --------- ------------------------------ 3.5/14.5 MB 1.7 MB/s eta 0:00:07
   --------- ------------------------------ 3.6/14.5 MB 1.7 MB/s eta 0:00:07
   ---------- ----------------------------- 3.7/14.5 MB 1.7 MB/s eta 0:00:07
   ---------- ----------------------------- 3.8/14.5 MB 1.7 MB/s eta 0:00:07
   ---------- ----------------------------- 3.9/14.5 MB 1.7 MB/s eta 0:00:07
   ----------- ---------------------------- 4.0/14.5 MB 1.7 MB/s eta 0:00:07
   ----------- ---------------------------- 4.1/14.5 MB 1.7 MB/s eta 0:00:07
   ----------- ---------------------------- 4.2/14.5 MB 1.7 MB/s eta 0:00:06
   ----------- ---------------------------- 4.3/14.5 MB 1.7 MB/s eta 0:00:06
   ------------ --------------------------- 4.4/14.5 MB 1.7 MB/s eta 0:00:06
   ------------ --------------------------- 4.5/14.5 MB 1.7 MB/s eta 0:00:06
   ------------ --------------------------- 4.6/14.5 MB 1.8 MB/s eta 0:00:06
   ------------- -------------------------- 4.8/14.5 MB 1.8 MB/s eta 0:00:06
   ------------- -------------------------- 4.9/14.5 MB 1.8 MB/s eta 0:00:06
   ------------- -------------------------- 4.9/14.5 MB 1.8 MB/s eta 0:00:06
   ------------- -------------------------- 5.0/14.5 MB 1.8 MB/s eta 0:00:06
   -------------- ------------------------- 5.2/14.5 MB 1.8 MB/s eta 0:00:06
   -------------- ------------------------- 5.2/14.5 MB 1.8 MB/s eta 0:00:06
   -------------- ------------------------- 5.3/14.5 MB 1.8 MB/s eta 0:00:06
   -------------- ------------------------- 5.4/14.5 MB 1.8 MB/s eta 0:00:05
   --------------- ------------------------ 5.5/14.5 MB 1.8 MB/s eta 0:00:05
   --------------- ------------------------ 5.6/14.5 MB 1.8 MB/s eta 0:00:05
   --------------- ------------------------ 5.7/14.5 MB 1.8 MB/s eta 0:00:05
   --------------- ------------------------ 5.7/14.5 MB 1.8 MB/s eta 0:00:05
   ---------------- ----------------------- 5.9/14.5 MB 1.8 MB/s eta 0:00:05
   ---------------- ----------------------- 6.0/14.5 MB 1.8 MB/s eta 0:00:05
   ---------------- ----------------------- 6.1/14.5 MB 1.8 MB/s eta 0:00:05
   ----------------- ---------------------- 6.2/14.5 MB 1.9 MB/s eta 0:00:05
   ----------------- ---------------------- 6.4/14.5 MB 1.9 MB/s eta 0:00:05
   ----------------- ---------------------- 6.5/14.5 MB 1.9 MB/s eta 0:00:05
   ------------------ --------------------- 6.6/14.5 MB 1.9 MB/s eta 0:00:05
   ------------------ --------------------- 6.7/14.5 MB 1.9 MB/s eta 0:00:05
   ------------------ --------------------- 6.9/14.5 MB 1.9 MB/s eta 0:00:04
   ------------------- -------------------- 7.0/14.5 MB 1.9 MB/s eta 0:00:04
   ------------------- -------------------- 7.1/14.5 MB 1.9 MB/s eta 0:00:04
   ------------------- -------------------- 7.2/14.5 MB 1.9 MB/s eta 0:00:04
   -------------------- ------------------- 7.3/14.5 MB 1.9 MB/s eta 0:00:04
   -------------------- ------------------- 7.5/14.5 MB 2.0 MB/s eta 0:00:04
   -------------------- ------------------- 7.5/14.5 MB 1.9 MB/s eta 0:00:04
   --------------------- ------------------ 7.7/14.5 MB 2.0 MB/s eta 0:00:04
   --------------------- ------------------ 7.8/14.5 MB 2.0 MB/s eta 0:00:04
   --------------------- ------------------ 7.9/14.5 MB 2.0 MB/s eta 0:00:04
   ---------------------- ----------------- 8.0/14.5 MB 2.0 MB/s eta 0:00:04
   ---------------------- ----------------- 8.1/14.5 MB 2.0 MB/s eta 0:00:04
   ---------------------- ----------------- 8.3/14.5 MB 2.0 MB/s eta 0:00:04
   ----------------------- ---------------- 8.4/14.5 MB 2.0 MB/s eta 0:00:03
   ----------------------- ---------------- 8.5/14.5 MB 2.0 MB/s eta 0:00:03
   ----------------------- ---------------- 8.6/14.5 MB 2.0 MB/s eta 0:00:03
   ----------------------- ---------------- 8.7/14.5 MB 2.0 MB/s eta 0:00:03
   ------------------------ --------------- 8.8/14.5 MB 2.0 MB/s eta 0:00:03
   ------------------------ --------------- 8.9/14.5 MB 2.0 MB/s eta 0:00:03
   ------------------------ --------------- 9.0/14.5 MB 2.0 MB/s eta 0:00:03
   ------------------------- -------------- 9.1/14.5 MB 2.0 MB/s eta 0:00:03
   ------------------------- -------------- 9.2/14.5 MB 2.0 MB/s eta 0:00:03
   ------------------------- -------------- 9.3/14.5 MB 2.0 MB/s eta 0:00:03
   -------------------------- ------------- 9.4/14.5 MB 2.0 MB/s eta 0:00:03
   -------------------------- ------------- 9.6/14.5 MB 2.0 MB/s eta 0:00:03
   -------------------------- ------------- 9.7/14.5 MB 2.0 MB/s eta 0:00:03
   --------------------------- ------------ 9.8/14.5 MB 2.0 MB/s eta 0:00:03
   --------------------------- ------------ 10.0/14.5 MB 2.1 MB/s eta 0:00:03
   --------------------------- ------------ 10.1/14.5 MB 2.1 MB/s eta 0:00:03
   ---------------------------- ----------- 10.2/14.5 MB 2.1 MB/s eta 0:00:03
   ---------------------------- ----------- 10.3/14.5 MB 2.1 MB/s eta 0:00:02
   ---------------------------- ----------- 10.3/14.5 MB 2.1 MB/s eta 0:00:02
   ---------------------------- ----------- 10.3/14.5 MB 2.1 MB/s eta 0:00:02
   ---------------------------- ----------- 10.3/14.5 MB 2.1 MB/s eta 0:00:02
   ----------------------------- ---------- 10.5/14.5 MB 2.1 MB/s eta 0:00:02
   ----------------------------- ---------- 10.6/14.5 MB 2.2 MB/s eta 0:00:02
   ----------------------------- ---------- 10.7/14.5 MB 2.2 MB/s eta 0:00:02
   ----------------------------- ---------- 10.8/14.5 MB 2.2 MB/s eta 0:00:02
   ------------------------------ --------- 11.0/14.5 MB 2.2 MB/s eta 0:00:02
   ------------------------------ --------- 11.2/14.5 MB 2.2 MB/s eta 0:00:02
   ------------------------------- -------- 11.3/14.5 MB 2.3 MB/s eta 0:00:02
   ------------------------------- -------- 11.4/14.5 MB 2.3 MB/s eta 0:00:02
   ------------------------------- -------- 11.6/14.5 MB 2.3 MB/s eta 0:00:02
   -------------------------------- ------- 11.7/14.5 MB 2.3 MB/s eta 0:00:02
   -------------------------------- ------- 11.8/14.5 MB 2.3 MB/s eta 0:00:02
   --------------------------------- ------ 12.0/14.5 MB 2.3 MB/s eta 0:00:02
   --------------------------------- ------ 12.2/14.5 MB 2.4 MB/s eta 0:00:01
   ---------------------------------- ----- 12.3/14.5 MB 2.4 MB/s eta 0:00:01
   ---------------------------------- ----- 12.5/14.5 MB 2.4 MB/s eta 0:00:01
   ---------------------------------- ----- 12.6/14.5 MB 2.4 MB/s eta 0:00:01
   ----------------------------------- ---- 12.8/14.5 MB 2.4 MB/s eta 0:00:01
   ----------------------------------- ---- 13.0/14.5 MB 2.4 MB/s eta 0:00:01
   ------------------------------------ --- 13.1/14.5 MB 2.4 MB/s eta 0:00:01
   ------------------------------------ --- 13.2/14.5 MB 2.4 MB/s eta 0:00:01
   ------------------------------------- -- 13.4/14.5 MB 2.4 MB/s eta 0:00:01
   ------------------------------------- -- 13.5/14.5 MB 2.5 MB/s eta 0:00:01
   ------------------------------------- -- 13.6/14.5 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 13.8/14.5 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 13.9/14.5 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 14.0/14.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  14.1/14.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  14.3/14.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  14.4/14.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  14.4/14.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 14.5/14.5 MB 2.5 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-8.4.0
Note: you may need to restart the kernel to use updated packages.

In [47]:
import mysql.connector

In [48]:

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="1234@"
)

print(mydb)

<mysql.connector.connection_cext.CMySQLConnection object at 0x00000213E49E9CD0>

In [55]:
pip install pymysql

Requirement already satisfied: pymysql in d:\anaconda\lib\site-packages (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [56]:
from sqlalchemy import create_engine

# Replace 'username', 'password', 'hostname', 'database' with your actual credentials
engine = create_engine('mysql://root:1234@localhost/sales')

ModuleNotFoundError: No module named 'MySQLdb'

In [57]:
# Assuming your DataFrame is named df
df.to_csv('new_orders.csv', index=False)  # Change 'data.csv' to your desired filename